spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
    initialization-mode: always

  flyway:
    enabled: true
    locations: classpath:db/migration

logging:
  level:
    org.springframework.jdbc.datasource.init.ScriptUtils: debug
    org.flywaydb.core.internal.command.DbValidate: debug